### ISSUE TITLE
A question about Github implementation.

### ISSUE THREAD

**Issue by yehia67** [chinchang/build-git-learn-git#1]
Hello @chinchang!
I have a question and I don't know where to ask. I am going to make a website exactly like GitHub but It will be decentralized (Implement it using Blockchain). But I don't know how to link between the local .git directory to a website? And do you know any library,npm package, tool...etc that implement all git functions? (And I could use it in a project for implementing Github)

**Comment by chinchang** [comment]
Hey, sorry I never got a chance to reply here. I am not much aware about blockchain, but there are certainly many implementation of GIT on npm. Eg. https://github.com/creationix/js-git https://github.com/isomorphic-git/isomorphic-git
